// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'ja'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	pages: {
		splash: {
			notice: {
				title: string
				text: string
			}
		}
	}
}

export type TranslationFunctions = {
	pages: {
		splash: {
			notice: {
				/**
				 * Please read before playing
				 */
				title: () => LocalizedString
				/**
				 * Flashing or light stimulation may cause eye pain or twitching. Please be careful if you are sensitive to light stimulation.
			Do not play for long periods of time and take appropriate breaks. It may cause headaches, vertigo, fatigue, and other health problems. If you experience any of those symptoms, stop playing. If symptoms do not improve, consult a physician.
			Please be sure to fully comply with the terms and conditions when playing the game, and make sure that all players are comfortable with online player interaction.
				 */
				text: () => LocalizedString
			}
		}
	}
}

export type Formatters = {}
